"""Default setup

Revision ID: 915b518714dc
Revises: 
Create Date: 2024-03-03 23:14:53.591375

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '915b518714dc'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('photo', sa.String(), nullable=True),
    sa.Column('max_capacity', sa.Integer(), nullable=True),
    sa.Column('is_registration_enabled', sa.Boolean(), nullable=True),
    sa.Column('first_division_invite_link', sa.String(), nullable=True),
    sa.Column('second_division_invite_link', sa.String(), nullable=True),
    sa.Column('first_division_chat_id', sa.String(), nullable=True),
    sa.Column('second_division_chat_id', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('faq_categories',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('parent_id', sa.BigInteger(), nullable=True),
    sa.Column('leaf_category', sa.Boolean(), nullable=False),
    sa.Column('category_answer', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['faq_categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('academic_group', sa.String(), nullable=True),
    sa.Column('instagram', sa.String(), nullable=True),
    sa.Column('is_banned', sa.Boolean(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('gender', sa.Enum('male', 'female', 'other_gender', 'nonbinary_gender', name='gender'), nullable=True),
    sa.PrimaryKeyConstraint('telegram_id')
    )
    op.create_table('event_registrations',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('event_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('is_ami_student', sa.Boolean(), nullable=False),
    sa.Column('codingame_username', sa.String(), nullable=False),
    sa.Column('is_approved', sa.Boolean(), nullable=False),
    sa.Column('division', sa.Integer(), nullable=False),
    sa.Column('invite_link', sa.String(), nullable=True),
    sa.Column('member_chat_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.telegram_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('event_registrations')
    op.drop_table('users')
    op.drop_table('faq_categories')
    op.drop_table('events')
    sa.Enum('male', 'female', 'other_gender', 'nonbinary_gender', name='gender').drop(op.get_bind(), checkfirst=False)
    # ### end Alembic commands ###
